# Generated by Django 6.0.1 on 2026-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_ownedcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedcard",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
